### ISSUE TITLE
Extracting the sample-level representation

### ISSUE THREAD

**Issue by emdann** [Center-for-Health-Data-Science/multiDGD#5]
We have to work on this, maybe adding some specific getters. 

As far as I can tell now the sample-level representation can be extracted using `model.correction_gmm.component_sample(n_sample=100)`. Can we add functionality to go from this to something like we have in Fig2? Happy to work on this if you point me at the code to make the batch level representations in `multiDGD_paper`

**Comment by viktoriaschuster** [comment]
`model.correction_gmm.component_sample()` does not extract learned representations, but samples from the distribution describing the **sample-level** latent features. I created a pull request adding a method to the model called `get_covariate_representation()` which works the same way as `get_representation()`.
